### ISSUE TITLE
Unofficial Proxy API Down

### ISSUE THREAD

**Issue by stevebauman** [stevebauman/github-summarizer#3]
Unfortunately it appears OpenAI has patched the whole the unofficial proxy API's were using:

https://github.com/transitive-bullshit/chatgpt-api/issues/453

API keys will now be necessary. I will be updating summarizer to work with the true OpenAI API.

**Comment by stevebauman** [comment]
Seems to be working again! 👍

**Comment by neelhabib** [comment]
not working
