### ISSUE TITLE
How to remove 3rd party proxy from this package?  

### ISSUE THREAD

**Issue by richlysakowski** [stevebauman/github-summarizer#4]
I would like to use it but don't want any security information to pass through any third-party proxy.  

The ability to remove this third-party proxy is important.

**Comment by stevebauman** [comment]
Yea totally understand. I think the third party service may be dead now, I'll update this with a new major version to use an OpenAI API key 👍

**Comment by stevebauman** [comment]
Just released [v2.0.0](https://github.com/stevebauman/github-summarizer/releases/tag/v2.0.0) and have completely removed third party proxies. We now use the real OpenAI API, along with real API keys.
